assets:
- GC
- USDCHF
- USDCAD
- GBPCAD
- NZDCAD
- NZDUSD
- GBPAUD
- NZDCHF
- CADCHF
- AUDUSD
- EURCHF
- EURCAD
- EURNZD
- GBPCHF
- GBPUSD
- EURAUD
- ^DJI
- BTCUSD
- AUDJPY
- NZDJPY
- GBPJPY
- USDJPY
