assets:
- AUDJPY
- AUDUSD
- BTCUSD
- CADCHF
- EURAUD
- EURCAD
- EURCHF
- EURNZD
- GBPAUD
- GBPCAD
- GBPCHF
- GBPJPY
- GBPUSD
- GC
- NZDCAD
- NZDCHF
- NZDJPY
- NZDUSD
- USDCAD
- USDCHF
- USDJPY
- ^DJI
