"""
config_docs.py — generate CONFIGURATION.md from the typed domain models.

Phase 9 of the configuration architecture refactor. The generator walks
the typed dataclass models in :mod:`configs.domain_models` and emits
a single Markdown reference table per domain. The output is checked
into the repo so contributors can browse settings without running the
engine.

Usage:
    python tools/config_docs.py               # write to docs/CONFIGURATION.md
    python tools/config_docs.py --stdout      # emit to stdout
"""

from __future__ import annotations

import argparse
import contextlib
import sys
from dataclasses import MISSING, fields, is_dataclass
from pathlib import Path
from typing import get_type_hints

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_PATH = REPO_ROOT / "docs" / "CONFIGURATION.md"


def _format_field(line: str) -> str:
    return f"| `{line}` | | |"


def _table_for_dataclass(cls) -> str:
    """Render a single config domain as a Markdown table."""
    name = cls.__name__
    doc = (cls.__doc__ or "").strip().splitlines()[0] if cls.__doc__ else "(no docstring)"
    out = f"## `{name}`\n\n{doc}\n\n"
    out += "| Field | Type | Default |\n|---|---|---|\n"
    hints = {}
    with contextlib.suppress(Exception):  # noqa: BLE001
        hints = get_type_hints(cls)
    for f in fields(cls):
        if f.name.startswith("_"):
            continue
        type_name = "Any"
        if f.name in hints:
            t = hints[f.name]
            type_name = _render_type(t)
        else:
            type_name = type(f.default).__name__
        if f.default is not MISSING:
            default_repr = repr(f.default)
        elif f.default_factory is not MISSING:
            default_repr = "(default_factory)"
        else:
            default_repr = "(required)"
        out += f"| `{f.name}` | `{type_name}` | `{default_repr}` |\n"
    out += "\n"
    return out


def _render_type(tp) -> str:
    """Render a type annotation into a compact human-readable name.

    Handles Union (including the Optional form), nested generics, and
    the typing module's Union sentinel (whose ``__name__`` shadows the
    type alias).
    """
    import typing

    origin = getattr(tp, "__origin__", None)
    args = getattr(tp, "__args__", ())

    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        if len(non_none) == 1:
            return f"Optional[{_render_type(non_none[0])}]"
        return "Union[" + ", ".join(_render_type(a) for a in args) + "]"

    if origin is not None:
        origin_name = getattr(origin, "__name__", str(origin))
        rendered_args = ", ".join(_render_type(a) for a in args)
        return f"{origin_name}[{rendered_args}]"

    name = getattr(tp, "__name__", None)
    if name is not None:
        return name
    return str(tp)


def render_markdown() -> str:
    """Render the full CONFIGURATION.md."""
    sys.path.insert(0, str(REPO_ROOT))

    try:
        risk_mod = __import__("configs.domain_models.risk", fromlist=["x"])
    except Exception as e:  # noqa: BLE001
        return f"# Configuration Reference\n\n*Generator import failed: {e}*\n"

    blocks = ["# EigenCapital Configuration Reference", ""]
    blocks.append(
        "Generated by `tools/config_docs.py` from the typed domain models.\n"
        "Regenerate after changing `configs/domain_models/*.py`.\n"
    )

    for cls_name in ("CapitalConfig", "HaltConfig", "SizingConfig", "ExitConfig", "SellOnlyConfig"):
        cls = getattr(risk_mod, cls_name, None)
        if cls is None or not is_dataclass(cls):
            continue
        try:
            blocks.append(_table_for_dataclass(cls))
        except Exception as e:  # noqa: BLE001
            blocks.append(f"\n*Skipped `{cls_name}` due to render error: {e}*\n")

    return "\n".join(blocks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of file")
    args = parser.parse_args()

    markdown = render_markdown()
    if args.stdout:
        print(markdown)
        return 0

    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(markdown)
    print(f"config_docs: wrote {DOCS_PATH} ({len(markdown.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
