/**
 * Mock SystemBundle for e2e tests.
 * This provides enough data for the full app shell to render
 * without a running backend on port 5000.
 */
export function createMockBundle() {
  return {
    meta: {
      version: '1.0.0',
      server_time: new Date().toISOString(),
      status: 'ok' as const,
      snapshot_time: new Date().toISOString(),
      snapshot_sequence_id: 42,
      max_live_age_seconds: 10,
      request_id: 'e2e-test-001',
    },
    snapshot: {
      contract_version: 1,
      sequence_id: 42,
      schema_version: '1.0.0',
      timestamp: new Date().toISOString(),
      portfolio: {
        total_value: 100000,
        mtm_value: 100500,
        total_return: 3.25,
        realized_value: 95000,
        realized_return: 2.0,
        unrealized_pnl: 500,
        capital: 50000,
        allocations: {
          EURUSD: 0.15,
          GBPUSD: 0.12,
          USDJPY: 0.10,
          AUDUSD: 0.08,
        },
        open_positions: 4,
        closed_trades: 120,
        admission: {
          n_intents: 15,
          n_admitted: 12,
          n_rejected: 3,
          budget_notional: 50000,
          admitted: ['EURUSD', 'GBPUSD', 'USDJPY'],
          rejected: ['GBPJPY'],
          rejection_reasons: { GBPJPY: 'PEK budget limit' },
          ranking_scores: { EURUSD: 85, GBPUSD: 72, USDJPY: 68 },
        },
      },
      assets: {
        EURUSD: createMockAsset('EURUSD'),
        GBPUSD: createMockAsset('GBPUSD'),
        USDJPY: createMockAsset('USDJPY'),
        AUDUSD: createMockAsset('AUDUSD'),
        NZDUSD: createMockAsset('NZDUSD'),
        USDCAD: createMockAsset('USDCAD'),
        EURJPY: createMockAsset('EURJPY'),
        GBPJPY: createMockAsset('GBPJPY', { sell_only: true }),
      },
      engine_status: {
        initialized: true,
        last_update: new Date().toISOString(),
        start_time: new Date(Date.now() - 86400000).toISOString(),
      },
      halt_conditions: {
        drawdown: 0.15,
        monthly_pf: 0.3,
        signal_drought: 0.05,
        prob_drift: 0.1,
      },
      emergency_halt: false,
      halt_reason: '',
      halt_detail: '',
      open_positions: null,
      risk_signals: null,
      shadow_actions: null,
      risk_parity: null,
      peak_portfolio_value: 102000,
      breaker_daily_pnl: null,
    },
    live: {
      health: {
        fetch_time: new Date().toISOString(),
        fetch_age_seconds: 1,
        is_fresh: true,
        assets: {},
        system_health: {
          mean_health_score: 0.78,
          n_assets: 8,
          healthiest_asset: 'EURUSD',
          weakest_asset: 'GBPJPY',
          n_healthy: 5,
          n_degraded: 2,
          n_critical: 1,
        },
      },
      mt5: {
        fetch_time: new Date().toISOString(),
        fetch_age_seconds: 2,
        is_fresh: true,
        connected: true,
        status: 'CONNECTED' as const,
        last_heartbeat: new Date().toISOString(),
        account: {
          portfolio_value: 100000,
          positions: [],
        },
      },
    },
  }
}

/** Mock attribution trades for the Analytics page PnL drill-down */
export function createMockAttributionTrades() {
  return [
    {
      trade_id: 't001',
      asset: 'EURUSD',
      entry_date: '2026-07-01T08:00:00Z',
      exit_date: '2026-07-02T16:00:00Z',
      side: 'long',
      entry_price: 1.1000,
      exit_price: 1.1050,
      realized_return: 0.0045,
      realized_pnl: 45.00,
      pred_signal: 'BUY',
      pred_confidence: 0.72,
      pred_archetype_at_entry: 'trend_follow',
      pred_regime_at_entry: 'RISK_ON',
      exec_entry_type: 'market',
      exec_entry_slippage_bps: 0.5,
      exec_deferred_bars: 0,
      exit_exit_reason: 'TP',
      exit_realized_r: 1.8,
      exit_mae: -0.002,
      exit_mfe: 0.006,
      exit_bars_held: 96,
      exit_archetype: 'trend_follow',
      friction_gap_fill: false,
      friction_partial_fill: false,
      friction_fill_qty_ratio: 1,
      friction_latency_bars: 0,
    },
    {
      trade_id: 't002',
      asset: 'GBPUSD',
      entry_date: '2026-06-30T10:00:00Z',
      exit_date: '2026-07-01T14:00:00Z',
      side: 'short',
      entry_price: 1.2650,
      exit_price: 1.2620,
      realized_return: 0.0024,
      realized_pnl: 24.00,
      pred_signal: 'SELL',
      pred_confidence: 0.65,
      pred_archetype_at_entry: 'mean_reversion',
      pred_regime_at_entry: 'RISK_ON',
      exec_entry_type: 'limit',
      exec_entry_slippage_bps: -0.3,
      exec_deferred_bars: 1,
      exit_exit_reason: 'TP',
      exit_realized_r: 1.2,
      exit_mae: -0.001,
      exit_mfe: 0.004,
      exit_bars_held: 28,
      exit_archetype: 'mean_reversion',
      friction_gap_fill: false,
      friction_partial_fill: false,
      friction_fill_qty_ratio: 1,
      friction_latency_bars: 0,
    },
  ]
}

export function createMockHealthResponse() {
  return {
    status: 'ok' as const,
    server_time: new Date().toISOString(),
    state_exists: true,
    state_file_age_s: 2,
    state_sequence_id: 42,
    engine_alive: true,
  }
}

function createMockAsset(name: string, overrides?: Record<string, unknown>) {
  return {
    metrics: {
      asset: name,
      current_value: 10000,
      settled_value: 9500,
      mtm_value: 10050,
      total_return: 2.5,
      settled_return: 1.8,
      mtm_return: 2.8,
      drawdown: -0.5,
      profit_factor: 1.65,
      win_rate: 0.58,
      n_trades: 30,
      n_signals: 120,
      signal_distribution: { BUY: 55, SELL: 45, FLAT: 20 },
      mean_confidence: 65.0,
      mean_prob_long: 0.52,
      mean_prob_short: 0.45,
      current_price: 1.1050,
      last_signal_date: new Date().toISOString(),
      monthly_pf: 0.4,
      position: {
        side: 'long' as const,
        entry: 1.1000,
        sl: 1.0950,
        tp: 1.1150,
        current_vol: 1000,
        unrealized_pnl: 50,
        sl_mult: 2.5,
        tp_mult: 1.5,
      },
      current_sl_mult: 2.5,
      current_tp_mult: 1.5,
      trade_log: [],
      feature_stability: { jaccard_top_10: 0.82, spearman_rank_corr: 0.70, penalty: 0.05, window_id: 'w-042' },
      exit_reasons: { tp_rate: 0.25, sl_rate: 0.45, trailing_sl_rate: 0.05, breakeven_rate: 0.05, flip_rate: 0.15, expiry_rate: 0.05, avg_r: 0.45 },
      archetype_stats: {
        trend_follow: { n: 15, win_rate: 0.65, avg_r: 0.8, sl_rate: 0.35, tp_rate: 0.25 },
        mean_reversion: { n: 10, win_rate: 0.50, avg_r: 0.4, sl_rate: 0.55, tp_rate: 0.15 },
      },
      meta_inference: null,
      scale_out_active: false,
      remaining_fraction: 1,
      scale_out_tiers: null,
      psi_drift: { per_feature: [], worst_classification: '', moderate_count: 0, severe_count: 0, psi_ok: true, penalty: 0 },
      sharpe_ratio: 1.15,
      psr_gt_0: 0.92,
      psr_gt_1: 0.35,
      min_trl: 25.0,
      crs: 0.82,
      hhi: 0.10,
    },
    halt: {
      halted: false,
      reasons: [],
      hard_reasons: [],
      soft_warnings: [],
      drawdown_ok: true,
      monthly_pf_ok: true,
      drought_ok: true,
      drift_ok: true,
      narrative_ok: true,
      liquidity_ok: true,
      psi_ok: true,
    },
    validity_state: 'GREEN',
    validity_exposure: 0.75,
    last_signal: {
      date: new Date().toISOString(),
      prob_long: 0.55,
      prob_short: 0.42,
      signal: 'BUY' as const,
      confidence: 65,
      close_price: 1.1050,
    },
    gate_override: false,
    signal_flip: false,
    final_signal: 'BUY',
    execution_state: 'ACTIVE',
    sl_mult: 2.5,
    tp_mult: 1.5,
    meta_confidence: null,
    meta_decision: null,
    feature_stability_jaccard: 0.82,
    feature_stability_spearman: 0.70,
    sell_only: false,
    tripwire_active: false,
    liquidity_regime: 'NORMAL',
    liquidity_sl_mult: 1.0,
    liquidity_size_scalar: 1.0,
    narrative_sl_mult: 1.0,
    narrative_size_scalar: 1.0,
    narrative_regime: 'RISK_ON',
    narrative_stale: false,
    regime_geometry: { TREND: { sl_mult: 2.0, tp_mult: 2.5 }, RANGING: { sl_mult: 3.0, tp_mult: 1.5 } },
    soft_warnings: [],
    stop_out_last_side: null,
    stop_out_last_cycle: null,
    last_regime_long_prob: 0.58,
    last_regime_label: 'TREND',
    sizing_chain: null,
    total_exits: 30,
    sl_exits: 14,
    sl_hit_rate: 0.4667,
    combined_sl_mult: 1.0,
    combined_size_scalar: 1.0,
    floor_active: false,
    ...(overrides ?? {}),
  }
}
